// AUTO-GENERATED by server.js at startup — safe to commit.
// cloud_name and upload_preset are NOT secrets:
//   - cloud_name appears in every Cloudinary CDN URL
//   - upload_preset is unsigned-only (cannot delete, cannot access account)
// API Key and API Secret are never written here — they stay in server.js only.
// Regenerated automatically when the server restarts; commit the latest version for GitHub Pages.
export const CLOUDINARY_CLOUD_NAME    = "its8g7qs";
export const CLOUDINARY_UPLOAD_PRESET = "pizza_menu_upload";
