// Runs at publish time (and can be run locally) to inject the Groq API key
// into a small generated client-side file. This project is a static site now
// (no server), so the key has to live in a file the browser can load — this
// script is the only place that ever touches the raw secret value; it reads
// it straight from the environment and writes it out, never prints it.
const fs = require('fs');
const path = require('path');

const key = process.env.GROQ_API_KEY || '';

if (!key) {
    console.warn('⚠️  GROQ_API_KEY is not set — the AI chat will not work until it is.');
}

const out = `// AUTO-GENERATED by build.js — do not edit by hand, do not commit.
window.GROQ_API_KEY = ${JSON.stringify(key)};
`;

const outPath = path.join(__dirname, 'admin', 'groq-key.generated.js');
fs.writeFileSync(outPath, out);
console.log(`Wrote ${outPath} (${key ? key.length + ' char key' : 'empty key'})`);
