// server.js
// Express server for New Pizza Hut & Live Cake — Billing Panel.
//
// Replaces the previous `node build.js && npx serve . -l 5000` workflow.
// This server was introduced to support server-side Pushover notifications
// so that Pushover credentials are never exposed in browser source.
//
// Responsibilities:
//   1. Inject GROQ_API_KEY into admin/groq-key.generated.js at startup
//      (previously done by build.js — that file is now unused).
//   2. POST /api/notify-order — proxy to Pushover API.
//   3. Serve all static project files from the root directory.
//
// AI UPDATE [2026-07-28] session 9:
//   Created — replaces static `npx serve` with Express so the Pushover
//   notification endpoint can exist without exposing credentials to the browser.
//   Deployment type must be changed from "static" to "autoscale" in .replit.
//
// AI UPDATE [2026-07-29] session 13:
//   POST /api/notify-order: accepts richer payload (orderId, customerPhone, items
//   array) and builds a fully-formatted notification message:
//     Customer, Phone, Table, Order #, itemised list.
//   Priority bumped to 2 (emergency) so the device is alerted immediately even
//   in Do Not Disturb / quiet hours.  retry=30 s, expire=300 s (Pushover
//   emergency priority requires both fields).
//
// AI UPDATE [2026-07-30]:
//   POST /api/notify-order: expire bumped 300 s → 3600 s (1 hour) per task spec.
//   POST /api/cancel-receipt: new endpoint — proxies cancel request to Pushover's
//     receipts/{receipt}/cancel.json API.  Keeps PUSHOVER_TOKEN server-side so it
//     is never exposed in browser source.  Called by js/incoming-orders.js when
//     the operator clicks "Acknowledge Order".

'use strict';

const express   = require('express');
const path      = require('path');
const fs        = require('fs');
const multer    = require('multer');
const { v2: cloudinary } = require('cloudinary');

const app  = express();
const PORT = process.env.PORT || 5000;

// ── 1. Inject GROQ API key at startup ─────────────────────────────────────────
// Mirrors what build.js used to do. Regenerates admin/groq-key.generated.js
// from the GROQ_API_KEY environment variable every time the server starts.
const groqKey    = process.env.GROQ_API_KEY || '';
const groqOutput = `// AUTO-GENERATED by server.js — do not edit by hand, do not commit.\nwindow.GROQ_API_KEY = ${JSON.stringify(groqKey)};\n`;
const groqPath   = path.join(__dirname, 'admin', 'groq-key.generated.js');
fs.writeFileSync(groqPath, groqOutput);

if (!groqKey) {
    console.warn('⚠️  GROQ_API_KEY is not set — AI chat will not work until it is.');
} else {
    console.log(`[server] Wrote groq-key.generated.js (${groqKey.length} char key)`);
}

// ── 2. Cloudinary configuration ───────────────────────────────────────────────
// AI UPDATE [2026-08-02]: Cloudinary replaces Firebase Storage for menu images.
// All three credentials come from environment variables only — never hardcoded.
// The browser never sees these values; uploads/deletes go through the two API
// endpoints below (/api/upload-menu-image, /api/delete-menu-image).
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME || '';
const CLOUDINARY_API_KEY    = process.env.CLOUDINARY_API_KEY    || '';
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET || '';

cloudinary.config({
    cloud_name: CLOUDINARY_CLOUD_NAME,
    api_key:    CLOUDINARY_API_KEY,
    api_secret: CLOUDINARY_API_SECRET,
    secure:     true,
});

// Upload preset name — safe to embed in client code (unsigned-only, no account access)
const CLOUDINARY_UPLOAD_PRESET = 'pizza_menu_upload';

if (!CLOUDINARY_CLOUD_NAME || !CLOUDINARY_API_KEY || !CLOUDINARY_API_SECRET) {
    console.warn('⚠️  Cloudinary credentials not set — menu image uploads will fail until ' +
        'CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, and CLOUDINARY_API_SECRET are configured.');
} else {
    console.log(`[server] Cloudinary configured (cloud: ${CLOUDINARY_CLOUD_NAME})`);

    // Inject public Cloudinary config into js/cloudinary-public.js so the browser
    // can use direct unsigned uploads from any host (GitHub Pages, Firebase Hosting, Replit).
    // cloud_name and upload_preset are NOT secrets — safe to commit and serve publicly.
    const publicConfigOutput =
        `// AUTO-GENERATED by server.js at startup — safe to commit.\n` +
        `// cloud_name and upload_preset are NOT secrets:\n` +
        `//   - cloud_name appears in every Cloudinary CDN URL\n` +
        `//   - upload_preset is unsigned-only (cannot delete, cannot access account)\n` +
        `// API Key and API Secret are never written here — they stay in server.js only.\n` +
        `// Regenerated automatically when the server restarts; commit the latest version for GitHub Pages.\n` +
        `export const CLOUDINARY_CLOUD_NAME    = ${JSON.stringify(CLOUDINARY_CLOUD_NAME)};\n` +
        `export const CLOUDINARY_UPLOAD_PRESET = ${JSON.stringify(CLOUDINARY_UPLOAD_PRESET)};\n`;
    fs.writeFileSync(path.join(__dirname, 'js', 'cloudinary-public.js'), publicConfigOutput);
    console.log(`[server] Wrote js/cloudinary-public.js (cloud: ${CLOUDINARY_CLOUD_NAME}, preset: ${CLOUDINARY_UPLOAD_PRESET})`);

    // Ensure the unsigned upload preset exists on Cloudinary (idempotent — safe to call on every start).
    // The preset enforces folder='menu-images' and allowed formats server-side so clients cannot abuse it.
    cloudinary.api.create_upload_preset({
        name:            CLOUDINARY_UPLOAD_PRESET,
        unsigned:        true,
        folder:          'menu-images',
        allowed_formats: 'jpg,jpeg,png,gif,webp,avif',
        max_file_size:   10485760, // 10 MB
    }).then(() => {
        console.log(`[cloudinary] Created unsigned upload preset: ${CLOUDINARY_UPLOAD_PRESET}`);
    }).catch(err => {
        // HTTP 409 or message containing "already exists" means the preset is already set up — OK
        const msg = (err.message || err.error?.message || '').toLowerCase();
        if (msg.includes('already exists') || err.http_code === 409 || err.error?.http_code === 409) {
            console.log(`[cloudinary] Upload preset already exists: ${CLOUDINARY_UPLOAD_PRESET}`);
        } else {
            console.warn(`[cloudinary] Could not create upload preset (non-fatal): ${err.message || JSON.stringify(err)}`);
        }
    });
}

// multer: in-memory storage — file buffer is piped to Cloudinary, no temp files written
const _upload = multer({
    storage:    multer.memoryStorage(),
    limits:     { fileSize: 10 * 1024 * 1024 }, // 10 MB hard cap
    fileFilter: (_req, file, cb) => {
        if (file.mimetype.startsWith('image/')) cb(null, true);
        else cb(new Error('Only image files are accepted'));
    },
});

// ── 3. Pushover credentials ───────────────────────────────────────────────────
const PUSHOVER_TOKEN = 'a8dwxwd298zj8uu5fotos3h8rhsu2c';
const PUSHOVER_USER  = 'u8cgozgvay9w3gmwp34p1od9ytir89';
const PUSHOVER_URL   = 'https://api.pushover.net/1/messages.json';

// ── Middleware ─────────────────────────────────────────────────────────────────
app.use(express.json());

// ── POST /api/upload-menu-image ───────────────────────────────────────────────
// AI UPDATE [2026-08-02]: Server-side Cloudinary upload proxy.
// Receives a multipart image from the browser, uploads to Cloudinary, returns:
//   { ok: true, url: <secure_url>, publicId: <public_id> }
// Optional body field `oldPublicId`: if present, the server deletes the old
// Cloudinary image (best-effort, fire-and-forget) as part of this call.
// Cloudinary credentials stay server-side — the browser only calls this endpoint.
app.post('/api/upload-menu-image', _upload.single('image'), async (req, res) => {
    if (!req.file) {
        return res.status(400).json({ ok: false, error: 'No image file provided' });
    }
    if (!CLOUDINARY_CLOUD_NAME || !CLOUDINARY_API_KEY || !CLOUDINARY_API_SECRET) {
        return res.status(503).json({ ok: false, error: 'Cloudinary credentials are not configured on this server' });
    }

    try {
        // Stream the buffer directly to Cloudinary (no temp file)
        const result = await new Promise((resolve, reject) => {
            const stream = cloudinary.uploader.upload_stream(
                {
                    folder:       'menu-images', // organises all menu images in one folder
                    quality:      'auto',         // intelligent quality reduction
                    fetch_format: 'auto',         // serve WebP/AVIF to supporting browsers
                },
                (error, result) => {
                    if (error) reject(error);
                    else       resolve(result);
                }
            );
            stream.end(req.file.buffer);
        });

        console.log(`[cloudinary] Uploaded: ${result.public_id} (${result.bytes} bytes)`);

        // Best-effort delete old image — fire-and-forget, non-blocking
        const oldPublicId = (req.body && req.body.oldPublicId || '').trim();
        if (oldPublicId) {
            cloudinary.uploader.destroy(oldPublicId)
                .then(() => console.log(`[cloudinary] Deleted old image: ${oldPublicId}`))
                .catch(err => console.warn(`[cloudinary] delete old image failed (non-fatal): ${err.message}`));
        }

        res.json({ ok: true, url: result.secure_url, publicId: result.public_id });
    } catch (err) {
        console.error('[cloudinary] upload failed:', err.message);
        res.status(500).json({ ok: false, error: err.message || 'Upload to Cloudinary failed' });
    }
});

// ── POST /api/delete-menu-image ───────────────────────────────────────────────
// AI UPDATE [2026-08-02]: Server-side Cloudinary delete proxy.
// Body: { publicId: string }
// Returns: { ok: true }
// Used by admin.js when the operator removes an image or replaces it with another.
// Credentials stay server-side.
app.post('/api/delete-menu-image', async (req, res) => {
    const { publicId } = req.body || {};
    if (!publicId || typeof publicId !== 'string') {
        return res.status(400).json({ ok: false, error: 'publicId (string) is required' });
    }
    if (!CLOUDINARY_CLOUD_NAME || !CLOUDINARY_API_KEY || !CLOUDINARY_API_SECRET) {
        return res.status(503).json({ ok: false, error: 'Cloudinary credentials are not configured on this server' });
    }

    try {
        await cloudinary.uploader.destroy(publicId);
        console.log(`[cloudinary] Deleted: ${publicId}`);
        res.json({ ok: true });
    } catch (err) {
        console.error('[cloudinary] delete failed:', err.message);
        res.status(500).json({ ok: false, error: err.message || 'Delete from Cloudinary failed' });
    }
});

// ── POST /api/notify-order ────────────────────────────────────────────────────
// Called by js/incoming-orders.js whenever a genuinely new customer order arrives.
// Request body (all optional fields — build message from whatever is present):
//   { orderId, tableId, customerName, customerPhone, items, itemCount, message }
//
// AI UPDATE [2026-07-29] session 13:
//   Richer payload accepted: orderId, customerPhone, items array.
//   Builds fully-formatted notification with all order details.
//   Priority: 2 (emergency) — device alerted immediately, bypasses DND/quiet hours.
//   Emergency priority requires retry + expire fields (Pushover API requirement).
app.post('/api/notify-order', async (req, res) => {
    const {
        orderId,
        tableId      = 'Unknown Table',
        customerName  = '',
        customerPhone = '',
        items         = [],
        itemCount,
        message
    } = req.body || {};

    const title = '🔔 New Order — New Pizza Hut & Live Cake';

    let msg;

    if (message) {
        // Explicit override (unused in normal flow but kept for future use)
        msg = message;
    } else {
        // Build rich, fully-formatted notification
        const lines = [];

        lines.push('New Order Received');
        lines.push('');

        if (customerName)  lines.push(`Customer: ${customerName}`);
        if (customerPhone) lines.push(`Phone: ${customerPhone}`);
        if (tableId)       lines.push(`Table: ${tableId}`);
        if (orderId)       lines.push(`Order #: ${orderId}`);

        if (items && items.length > 0) {
            lines.push('');
            lines.push('Items:');
            items.forEach(item => {
                const qty  = item.quantity || 1;
                const name = item.name     || 'Unknown Item';
                lines.push(`• ${name} ×${qty}`);
            });
        } else if (itemCount) {
            lines.push('');
            lines.push(`Items: ${itemCount} item${itemCount !== 1 ? 's' : ''}`);
        }

        msg = lines.join('\n');
    }

    console.log(`[notify] Sending Pushover (priority 2/emergency):\n  Title: "${title}"\n  Body preview: "${msg.slice(0, 120)}..."`);

    try {
        const response = await fetch(PUSHOVER_URL, {
            method:  'POST',
            headers: { 'Content-Type': 'application/json' },
            body:    JSON.stringify({
                token:    PUSHOVER_TOKEN,
                user:     PUSHOVER_USER,
                title,
                message:  msg,
                sound:    'Notification',   // capital N — exact identifier per /1/sounds.json ("Order's notification")
                priority: 2,    // Emergency: highest priority, bypasses DND/quiet hours
                // AI UPDATE [2026-07-31]: retry corrected 5 → 30. Pushover requires
                // retry ≥ 30 s for priority=2. This route is currently unused (client
                // routes through the Cloudflare Worker via httpsCallable), but fixed
                // for correctness in case it is re-enabled.
                retry:    30,   // Resend every 30 s — Pushover minimum for priority 2
                expire:   3600  // Stop retrying after 1 hour (required for priority 2)
            })
        });

        const result = await response.json();

        if (result.status === 1) {
            console.log('[notify] Pushover delivered ✓ receipt:', result.receipt);
            res.json({ ok: true, receipt: result.receipt });
        } else {
            console.error('[notify] Pushover API error:', result);
            res.status(500).json({ ok: false, errors: result.errors });
        }
    } catch (err) {
        console.error('[notify] Pushover request failed:', err.message);
        res.status(500).json({ ok: false, error: err.message });
    }
});

// ── POST /api/cancel-receipt ──────────────────────────────────────────────────
// Called by js/incoming-orders.js when the operator clicks "Acknowledge Order".
// Proxies the cancel request to Pushover's receipts/{receipt}/cancel.json API.
// PUSHOVER_TOKEN is kept server-side — never exposed in browser source.
//
// AI UPDATE [2026-07-30]:
//   New endpoint — part of the complete emergency acknowledgement workflow.
//   Request body: { receipt: string }
//   On success: Pushover stops re-notifying; returns { ok: true }
//   On failure: returns { ok: false, error/errors }
app.post('/api/cancel-receipt', async (req, res) => {
    const { receipt } = req.body || {};

    if (!receipt || typeof receipt !== 'string' || !/^[a-zA-Z0-9]+$/.test(receipt)) {
        console.warn('[cancel] Invalid or missing receipt in request body');
        return res.status(400).json({ ok: false, error: 'Invalid or missing receipt' });
    }

    console.log(`[cancel] Cancel request received for receipt: ${receipt}`);

    try {
        // AI UPDATE [2026-07-31]: Changed Content-Type to application/x-www-form-urlencoded.
        // Pushover's messages.json endpoint accepts JSON, but the receipts cancel endpoint
        // only documents form-encoded parameters.  Sending JSON caused Pushover to ignore
        // the token field (body not parsed), returning status:0, so the notification was
        // never actually cancelled.  Form-encoded is always accepted by all Pushover endpoints.
        const response = await fetch(
            `https://api.pushover.net/1/receipts/${receipt}/cancel.json`,
            {
                method:  'POST',
                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                body:    `token=${encodeURIComponent(PUSHOVER_TOKEN)}`
            }
        );

        console.log(`[cancel] Pushover cancel response status: ${response.status}`);
        const result = await response.json();
        console.log('[cancel] Pushover cancel response body:', result);

        if (result.status === 1) {
            console.log(`[cancel] Emergency notification cancelled ✓ receipt: ${receipt}`);
            res.json({ ok: true });
        } else {
            console.error('[cancel] Pushover cancel API error:', result);
            res.status(500).json({ ok: false, errors: result.errors });
        }
    } catch (err) {
        console.error('[cancel] Cancel request failed:', err.message);
        res.status(500).json({ ok: false, error: err.message });
    }
});

// ── 3. Serve static files ─────────────────────────────────────────────────────
// HTML pages always served fresh; JS/CSS/assets use default permissive caching.
// The service worker (sw.js) is served with no-cache so installs are always
// up-to-date — browsers will detect version bumps on every navigation.
app.use((req, res, next) => {
    const p = req.path;
    if (p.endsWith('.html') || p === '/' || p.endsWith('sw.js')) {
        res.setHeader('Cache-Control', 'no-cache');
    }
    next();
});
app.use(express.static(__dirname));

// ── Start ──────────────────────────────────────────────────────────────────────
app.listen(PORT, '0.0.0.0', () => {
    console.log(`
  ┌────────────────────────────────────────┐
  │  Pizza Hut Billing Panel               │
  │  Serving!                              │
  │  - Local:   http://0.0.0.0:${PORT}        │
  └────────────────────────────────────────┘
`);
});
