// server.js
// Express server for New Pizza Hut & Live Cake — Billing Panel.
//
// Replaces the previous `node build.js && npx serve . -l 5000` workflow.
// This server was introduced to support server-side Pushover notifications
// so that Pushover credentials are never exposed in browser source.
//
// Responsibilities:
//   1. Inject GROQ_API_KEY into admin/groq-key.generated.js at startup
//      (previously done by build.js — that file is now unused).
//   2. POST /api/notify-order — proxy to Pushover API.
//   3. Serve all static project files from the root directory.
//
// AI UPDATE [2026-07-28] session 9:
//   Created — replaces static `npx serve` with Express so the Pushover
//   notification endpoint can exist without exposing credentials to the browser.
//   Deployment type must be changed from "static" to "autoscale" in .replit.
//
// AI UPDATE [2026-07-29] session 13:
//   POST /api/notify-order: accepts richer payload (orderId, customerPhone, items
//   array) and builds a fully-formatted notification message:
//     Customer, Phone, Table, Order #, itemised list.
//   Priority bumped to 2 (emergency) so the device is alerted immediately even
//   in Do Not Disturb / quiet hours.  retry=30 s, expire=300 s (Pushover
//   emergency priority requires both fields).
//
// AI UPDATE [2026-07-30]:
//   POST /api/notify-order: expire bumped 300 s → 3600 s (1 hour) per task spec.
//   POST /api/cancel-receipt: new endpoint — proxies cancel request to Pushover's
//     receipts/{receipt}/cancel.json API.  Keeps PUSHOVER_TOKEN server-side so it
//     is never exposed in browser source.  Called by js/incoming-orders.js when
//     the operator clicks "Acknowledge Order".

'use strict';

const express = require('express');
const path    = require('path');
const fs      = require('fs');

const app  = express();
const PORT = process.env.PORT || 5000;

// ── 1. Inject GROQ API key at startup ─────────────────────────────────────────
// Mirrors what build.js used to do. Regenerates admin/groq-key.generated.js
// from the GROQ_API_KEY environment variable every time the server starts.
const groqKey    = process.env.GROQ_API_KEY || '';
const groqOutput = `// AUTO-GENERATED by server.js — do not edit by hand, do not commit.\nwindow.GROQ_API_KEY = ${JSON.stringify(groqKey)};\n`;
const groqPath   = path.join(__dirname, 'admin', 'groq-key.generated.js');
fs.writeFileSync(groqPath, groqOutput);

if (!groqKey) {
    console.warn('⚠️  GROQ_API_KEY is not set — AI chat will not work until it is.');
} else {
    console.log(`[server] Wrote groq-key.generated.js (${groqKey.length} char key)`);
}

// ── 2. Pushover credentials ───────────────────────────────────────────────────
const PUSHOVER_TOKEN = 'a8dwxwd298zj8uu5fotos3h8rhsu2c';
const PUSHOVER_USER  = 'u8cgozgvay9w3gmwp34p1od9ytir89';
const PUSHOVER_URL   = 'https://api.pushover.net/1/messages.json';

// ── Middleware ─────────────────────────────────────────────────────────────────
app.use(express.json());

// ── POST /api/notify-order ────────────────────────────────────────────────────
// Called by js/incoming-orders.js whenever a genuinely new customer order arrives.
// Request body (all optional fields — build message from whatever is present):
//   { orderId, tableId, customerName, customerPhone, items, itemCount, message }
//
// AI UPDATE [2026-07-29] session 13:
//   Richer payload accepted: orderId, customerPhone, items array.
//   Builds fully-formatted notification with all order details.
//   Priority: 2 (emergency) — device alerted immediately, bypasses DND/quiet hours.
//   Emergency priority requires retry + expire fields (Pushover API requirement).
app.post('/api/notify-order', async (req, res) => {
    const {
        orderId,
        tableId      = 'Unknown Table',
        customerName  = '',
        customerPhone = '',
        items         = [],
        itemCount,
        message
    } = req.body || {};

    const title = '🔔 New Order — New Pizza Hut & Live Cake';

    let msg;

    if (message) {
        // Explicit override (unused in normal flow but kept for future use)
        msg = message;
    } else {
        // Build rich, fully-formatted notification
        const lines = [];

        lines.push('New Order Received');
        lines.push('');

        if (customerName)  lines.push(`Customer: ${customerName}`);
        if (customerPhone) lines.push(`Phone: ${customerPhone}`);
        if (tableId)       lines.push(`Table: ${tableId}`);
        if (orderId)       lines.push(`Order #: ${orderId}`);

        if (items && items.length > 0) {
            lines.push('');
            lines.push('Items:');
            items.forEach(item => {
                const qty  = item.quantity || 1;
                const name = item.name     || 'Unknown Item';
                lines.push(`• ${name} ×${qty}`);
            });
        } else if (itemCount) {
            lines.push('');
            lines.push(`Items: ${itemCount} item${itemCount !== 1 ? 's' : ''}`);
        }

        msg = lines.join('\n');
    }

    console.log(`[notify] Sending Pushover (priority 2/emergency):\n  Title: "${title}"\n  Body preview: "${msg.slice(0, 120)}..."`);

    try {
        const response = await fetch(PUSHOVER_URL, {
            method:  'POST',
            headers: { 'Content-Type': 'application/json' },
            body:    JSON.stringify({
                token:    PUSHOVER_TOKEN,
                user:     PUSHOVER_USER,
                title,
                message:  msg,
                sound:    'notification',
                priority: 2,    // Emergency: highest priority, bypasses DND/quiet hours
                retry:    30,   // Resend every 30 s until acknowledged (required for priority 2)
                expire:   3600  // Stop retrying after 1 hour (required for priority 2)
            })
        });

        const result = await response.json();

        if (result.status === 1) {
            console.log('[notify] Pushover delivered ✓ receipt:', result.receipt);
            res.json({ ok: true, receipt: result.receipt });
        } else {
            console.error('[notify] Pushover API error:', result);
            res.status(500).json({ ok: false, errors: result.errors });
        }
    } catch (err) {
        console.error('[notify] Pushover request failed:', err.message);
        res.status(500).json({ ok: false, error: err.message });
    }
});

// ── POST /api/cancel-receipt ──────────────────────────────────────────────────
// Called by js/incoming-orders.js when the operator clicks "Acknowledge Order".
// Proxies the cancel request to Pushover's receipts/{receipt}/cancel.json API.
// PUSHOVER_TOKEN is kept server-side — never exposed in browser source.
//
// AI UPDATE [2026-07-30]:
//   New endpoint — part of the complete emergency acknowledgement workflow.
//   Request body: { receipt: string }
//   On success: Pushover stops re-notifying; returns { ok: true }
//   On failure: returns { ok: false, error/errors }
app.post('/api/cancel-receipt', async (req, res) => {
    const { receipt } = req.body || {};

    if (!receipt || typeof receipt !== 'string' || !/^[a-zA-Z0-9]+$/.test(receipt)) {
        console.warn('[cancel] Invalid or missing receipt in request body');
        return res.status(400).json({ ok: false, error: 'Invalid or missing receipt' });
    }

    console.log(`[cancel] Cancel request received for receipt: ${receipt}`);

    try {
        const response = await fetch(
            `https://api.pushover.net/1/receipts/${receipt}/cancel.json`,
            {
                method:  'POST',
                headers: { 'Content-Type': 'application/json' },
                body:    JSON.stringify({ token: PUSHOVER_TOKEN })
            }
        );

        console.log(`[cancel] Pushover cancel response status: ${response.status}`);
        const result = await response.json();
        console.log('[cancel] Pushover cancel response body:', result);

        if (result.status === 1) {
            console.log(`[cancel] Emergency notification cancelled ✓ receipt: ${receipt}`);
            res.json({ ok: true });
        } else {
            console.error('[cancel] Pushover cancel API error:', result);
            res.status(500).json({ ok: false, errors: result.errors });
        }
    } catch (err) {
        console.error('[cancel] Cancel request failed:', err.message);
        res.status(500).json({ ok: false, error: err.message });
    }
});

// ── 3. Serve static files ─────────────────────────────────────────────────────
// HTML pages always served fresh; JS/CSS/assets use default permissive caching.
// The service worker (sw.js) is served with no-cache so installs are always
// up-to-date — browsers will detect version bumps on every navigation.
app.use((req, res, next) => {
    const p = req.path;
    if (p.endsWith('.html') || p === '/' || p.endsWith('sw.js')) {
        res.setHeader('Cache-Control', 'no-cache');
    }
    next();
});
app.use(express.static(__dirname));

// ── Start ──────────────────────────────────────────────────────────────────────
app.listen(PORT, '0.0.0.0', () => {
    console.log(`
  ┌────────────────────────────────────────┐
  │  Pizza Hut Billing Panel               │
  │  Serving!                              │
  │  - Local:   http://0.0.0.0:${PORT}        │
  └────────────────────────────────────────┘
`);
});
