// server.js
// Express server for New Pizza Hut & Live Cake — Billing Panel.
//
// Replaces the previous `node build.js && npx serve . -l 5000` workflow.
// This server was introduced to support server-side Pushover notifications
// so that Pushover credentials are never exposed in browser source.
//
// Responsibilities:
//   1. Inject GROQ_API_KEY into admin/groq-key.generated.js at startup
//      (previously done by build.js — that file is now unused).
//   2. POST /api/notify-order — proxy to Pushover API.
//   3. Serve all static project files from the root directory.
//
// AI UPDATE [2026-07-28] session 9:
//   Created — replaces static `npx serve` with Express so the Pushover
//   notification endpoint can exist without exposing credentials to the browser.
//   Deployment type must be changed from "static" to "autoscale" in .replit.

'use strict';

const express = require('express');
const path    = require('path');
const fs      = require('fs');

const app  = express();
const PORT = process.env.PORT || 5000;

// ── 1. Inject GROQ API key at startup ─────────────────────────────────────────
// Mirrors what build.js used to do. Regenerates admin/groq-key.generated.js
// from the GROQ_API_KEY environment variable every time the server starts.
const groqKey    = process.env.GROQ_API_KEY || '';
const groqOutput = `// AUTO-GENERATED by server.js — do not edit by hand, do not commit.\nwindow.GROQ_API_KEY = ${JSON.stringify(groqKey)};\n`;
const groqPath   = path.join(__dirname, 'admin', 'groq-key.generated.js');
fs.writeFileSync(groqPath, groqOutput);

if (!groqKey) {
    console.warn('⚠️  GROQ_API_KEY is not set — AI chat will not work until it is.');
} else {
    console.log(`[server] Wrote groq-key.generated.js (${groqKey.length} char key)`);
}

// ── 2. Pushover credentials ───────────────────────────────────────────────────
const PUSHOVER_TOKEN = 'a8dwxwd298zj8uu5fotos3h8rhsu2c';
const PUSHOVER_USER  = 'u8cgozgvay9w3gmwp34p1od9ytir89';
const PUSHOVER_URL   = 'https://api.pushover.net/1/messages.json';

// ── Middleware ─────────────────────────────────────────────────────────────────
app.use(express.json());

// ── POST /api/notify-order ────────────────────────────────────────────────────
// Called by js/incoming-orders.js whenever a genuinely new customer order arrives.
// Request body (all optional):
//   { tableId, customerName, itemCount, message }
// Sends a Pushover push notification with a dynamic message.
// The "message" field overrides the auto-generated message if supplied.
app.post('/api/notify-order', async (req, res) => {
    const { tableId, customerName, itemCount, message } = req.body || {};

    // Build dynamic notification message
    let title = '🔔 New Order — New Pizza Hut & Live Cake';
    let msg   = 'New order received for New Pizza Hut and Live Cake!';

    if (tableId) {
        msg = `New order for ${tableId}`;
        if (customerName) msg += ` — ${customerName}`;
        if (itemCount)    msg += ` (${itemCount} item${itemCount !== 1 ? 's' : ''})`;
    }

    // Explicit message overrides the auto-built one
    if (message) msg = message;

    console.log(`[notify] Sending Pushover: "${msg}"`);

    try {
        const response = await fetch(PUSHOVER_URL, {
            method:  'POST',
            headers: { 'Content-Type': 'application/json' },
            body:    JSON.stringify({
                token:   PUSHOVER_TOKEN,
                user:    PUSHOVER_USER,
                title,
                message: msg,
                sound:   'notification'
            })
        });

        const result = await response.json();

        if (result.status === 1) {
            console.log('[notify] Pushover delivered ✓');
            res.json({ ok: true });
        } else {
            console.error('[notify] Pushover API error:', result);
            res.status(500).json({ ok: false, errors: result.errors });
        }
    } catch (err) {
        console.error('[notify] Pushover request failed:', err.message);
        res.status(500).json({ ok: false, error: err.message });
    }
});

// ── 3. Serve static files ─────────────────────────────────────────────────────
// HTML pages always served fresh; JS/CSS/assets use default permissive caching.
// The service worker (sw.js) is served with no-cache so installs are always
// up-to-date — browsers will detect version bumps on every navigation.
app.use((req, res, next) => {
    const p = req.path;
    if (p.endsWith('.html') || p === '/' || p.endsWith('sw.js')) {
        res.setHeader('Cache-Control', 'no-cache');
    }
    next();
});
app.use(express.static(__dirname));

// ── Start ──────────────────────────────────────────────────────────────────────
app.listen(PORT, '0.0.0.0', () => {
    console.log(`
  ┌────────────────────────────────────────┐
  │  Pizza Hut Billing Panel               │
  │  Serving!                              │
  │  - Local:   http://0.0.0.0:${PORT}        │
  └────────────────────────────────────────┘
`);
});
